### ISSUE TITLE
Ferguson code deemed ok by Edinburgh 

### ISSUE THREAD

**Issue by timcdlucas** [timcdlucas/unit_test_for_infectious_disease#9]
https://www.nature.com/articles/d41586-020-01685-y

**Comment by t-pollington** [comment]
nice spot

Sorry I didn't get a chance to check our covidringbp code yet. Codecheck is coming for us!

Something you could add to our unittesting paper is a change on emphasis. So far we have used unit testing as a way to convince ourselves that we can no longer find more bugs, and thus use this to prove others there are none. However despite us talking of Ferguson's mid March work as not being reproducible, we don't really mention how an independent someone can reproduce the results of a paper by using the code. This is more about results reproducibility.

Also this is not reproducible at the level of the original coder who knows what it does. Instead for the ultimate test, documentation should be provided and sensible code nomenclature, so that given reading the Methods of the paper alone, an independent user should be able to run the code and get the same results. Of course the way the code is written, normally for a specific model purpose in mind means that as the tester reads the code they will coaxed into the coder's thinking which follows a certain route of reasoning. So this type of testing can only reveal if the code does what the model says it should, rather than if the model makes sense in its own right.

We could expand a little on this:
comments in the code which link the code output to text or figures or tables in the manuscript.
Greek Unicode in code script to aid readability e.g. RMarkdown or Python with Unicode support
Pair working: coder watches independent working through the code. Independent works through the code and ideally it should be ordered in the order that results appear in the paper. If any problem is reached the independent should stop and seek clarification. They should not work on further forward in case the poorly ordered future code explains how they should do it.
All results in the paper, table cell contents and figures should be output in the code.
For intermediate results that are too large to store and require running the code a considerable time to produce, an approximate runtime should be given.
Package versions, software language version, OS and if a low-level code then the compiler.
Do we know/can link to the exact tests Codecheck do e.g. https://codecheck.org.uk/process/. After all they should be transparent in how they do their testing so people can design reproducible-friendly code.

What's the status on the unittesting paper? Presuming you're run ragged with covidringbp. I think some of these developments would be noteworthy to include as a sentence, but just keep the paper about unit testing for now.

________________________________

**Comment by timcdlucas** [comment]
I'll have to read this more carefully tomorrow.

But the status is I'm waiting for comments from Deirdre. I'm happy to just spruce up and submit without further comments from her but (especially as my first paper with her) I'm just trying to work out what she's happy with as I go along.
